// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.543
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import "github.com/RATIU5/chewbacca/internal/view/layout"

func ShowIndex() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
			if !templ_7745c5c3_IsBuffer {
				templ_7745c5c3_Buffer = templ.GetBuffer()
				defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"w-full mx-auto flex flex-col justify-center items-center max-w-xl lg:max-w-3xl mt-72 pb-32\"><div class=\"w-full flex flex-col items-center px-4\"><img src=\"/assets/img/chewbacca.png\" alt=\"Chewbacca\" class=\"w-32 h-32 mb-4 object-cover\"><div class=\"w-full text-center mb-4\"><h1 class=\"text-4xl uppercase mb-1\">Chewbacca</h1><p class=\"text-sm text-neutral-400\">The 404 asset locator</p></div><form class=\"w-full flex flex-col gap-4\" hx-post=\"/process-addr\" hx-target=\"#formResponse\" hx-swap=\"innerHTML\" hx-indicator=\"#spinner\" hx-disabled-elt=\"#submitBtn\"><div class=\"w-full\"><input type=\"text\" name=\"addr\" id=\"addr\" placeholder=\"https://www.example.com/\" class=\"bg-neutral-800 border border-solid border-neutral-700 h-12 px-4 w-full mt-4 rounded-md lg:mb-0 outline-[#FF9908] shadow-none\" required></div><div class=\"flex flex-col items-center md:flex-row-reverse\"><button type=\"submit\" id=\"submitBtn\" class=\"flex justify-center items-center max-w-md bg-neutral-800 text-sm px-4 mb-2 py-2 w-36 h-12 text-neutral-300 rounded-md hover:bg-neutral-700 disabled:hover:bg-neutral-800 active:bg-neutral-700 transition ease\"><svg class=\"spinner animate-spin\" id=\"spinner\" xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M21 12a9 9 0 1 1-6.219-8.56\"></path></svg> <span>Rrrrr-ghghghgh!</span></button></div></form></div><div id=\"formResponse\" class=\"w-full\"></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if !templ_7745c5c3_IsBuffer {
				_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
			}
			return templ_7745c5c3_Err
		})
		templ_7745c5c3_Err = layout.Base().Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
